version: '3.8'

services:
  postgres:
    container_name: woolba_postgresql
    image: postgres:alpine
    environment:
      POSTGRES_DB: woolba
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - /Users/woolbapro/Database/postgresql_data:/var/lib/postgresql/data
  
  mongo:
    container_name: woolba_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /Users/woolbapro/Database/mongo_data:/data/db
      
  redis:
    container_name: woolba_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /Users/woolbapro/Database/redis_data:/data
    platform: linux/amd64

  kafka:
    container_name: woolba_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    platform: linux/amd64

  zookeeper:
    container_name: woolba_zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    platform: linux/amd64

volumes:
  postgres_data:
  redis_data:
  mongo_data:
